# Generated by Django 2.2.1 on 2019-05-12 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, null=True)),
                ('userID', models.TextField(blank=True, null=True)),
                ('Designation', models.TextField(blank=True, null=True)),
                ('description', models.TextField(default='I AM A HACKER')),
            ],
        ),
    ]
