# Generated by Django 2.2.1 on 2019-05-12 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='description',
            field=models.TextField(default='I AM A HACKER BUT HONEST'),
        ),
    ]
